apiVersion: v1
kind: Service
metadata:
  name: {{ include "decider-helm.fullname" . }}-client-cluster-ip-service
  labels:
  {{- include "decider-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.clientClusterIpService.type }}
  selector:
    app: decider-web
  {{- include "decider-helm.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.clientClusterIpService.ports | toYaml | nindent 2 -}}