apiVersion: v1
kind: Service
metadata:
  name: {{ include "decider-helm.fullname" . }}-db-service
  labels:
    app: db-service
  {{- include "decider-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dbService.type }}
  selector:
    app: decider-db
  {{- include "decider-helm.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.dbService.ports | toYaml | nindent 2 -}}