apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "decider-helm.fullname" . }}-debs-postgres-claim
  labels:
    component.service: db-data
  {{- include "decider-helm.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.debsPostgresClaim.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.debsPostgresClaim.storageClass | quote }}