apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "decider-helm.fullname" . }}-ebs-sc
  labels:
  {{- include "decider-helm.labels" . | nindent 4 }}
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer