apiVersion: v1
kind: Secret
metadata:
  name: {{ include "decider-helm.fullname" . }}-postgres-db-credentials
  labels:
  {{- include "decider-helm.labels" . | nindent 4 }}
data:
  db_password: {{ required "postgresDbCredentials.dbPassword is required" .Values.postgresDbCredentials.dbPassword
    | b64enc | quote }}
  db_username: {{ required "postgresDbCredentials.dbUsername is required" .Values.postgresDbCredentials.dbUsername
    | b64enc | quote }}
type: Opaque